name: Benchmark

on:
  push:
    branches:
      - master
      - benchmark

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Build artifacts
        run: mvn clean install

      - name: Run Benchmark Sequentially
        run: java -jar target/benchmarks.jar -rf text -rff sequential.log -i 4 -wi 4 -f 1 -r 2 -w 2 -tu s  --jvmArgs "-Xms6G -Xmx6G -XX:ActiveProcessorCount=1" sequential -p COLLECTION_SIZE=5,50,500,5000,50000,500000

      - name: Run Benchmark in Parallel [2-Cores]
        run: java -jar target/benchmarks.jar -rf text -rff parallel[2].log -i 4 -wi 4 -f 1 -r 2 -w 2 -tu s  --jvmArgs "-Xms6G -Xmx6G -XX:ActiveProcessorCount=2" parallel -p COLLECTION_SIZE=5,50,500,5000,50000,500000 -p PARALLELISM=2

      - name: Run Benchmark in Parallel [4-Cores]
        run: java -jar target/benchmarks.jar -rf text -rff parallel[4].log -i 4 -wi 4 -f 1 -r 2 -w 2 -tu s  --jvmArgs "-Xms6G -Xmx6G -XX:ActiveProcessorCount=4" parallel -p COLLECTION_SIZE=5,50,500,5000,50000,500000 -p PARALLELISM=4

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: Parallel_Benchmarks
          path: ./*.log
